services:
  - type: web
    name: dealagent007
    runtime: python
    plan: free
    buildCommand: uv sync --frozen && uv cache prune --ci
    startCommand: uvicorn src.service.service:app --host 0.0.0.0 --port 8000
    envVars:
      - key: AUTH_SECRET
        value: your-secret-here
      - key: PYTHONPATH
        value: src
