services:
  - type: web
    name: deal-agent-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn src.service.service:app --host 0.0.0.0 --port 10000
    autoDeploy: true
