services:
  - type: web
    name: dealagent007
    runtime: python
    plan: free
    buildCommand: uv sync --frozen && uv cache prune --ci
    startCommand: bash startup.sh
    envVars:
      - key: AUTH_SECRET
        fromEnvVar: AUTH_SECRET

      - key: COMPATIBLE_API_KEY
        fromEnvVar: COMPATIBLE_API_KEY

      - key: COMPATIBLE_MODEL
        value: openai/gpt-4o

      - key: COMPATIBLE_BASE_URL
        value: https://openrouter.ai/api/v1

      - key: DEFAULT_MODEL
        value: gpt-4o

      - key: OPENAI_API_KEY
        fromEnvVar: OPENAI_API_KEY

      - key: USE_FAKE_MODEL
        value: "false"

      - key: USE_AWS_BEDROCK
        value: "false"

      - key: HOST
        value: 0.0.0.0

      - key: PORT
        value: "8080"

      - key: MODE
        value: dev

      - key: DATABASE_TYPE
        value: sqlite

      - key: SQLITE_DB_PATH
        value: ./data/dev.sqlite
