services:
  - type: web
    name: dealagent007
    runtime: python
    plan: free
    buildCommand: uv sync --frozen && uv cache prune --ci
    startCommand: bash startup.sh
    envVars:
      - key: AUTH_SECRET
        value: your-secret-here
